<a href="https://colab.research.google.com/github/MATHKIMS/DSAC_license/blob/main/%5BDSAC_2%EC%A3%BC%EC%B0%A8%5Dgg_03_%5B2%EC%A3%BC%EC%B0%A8_(2)%5D_numpy%EC%99%80_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 

## 리스트와 배열

In [1]:
import numpy as np
list_1=[1,2,10]
type(list_1)
list_1*3 #리스트의 연산은 리스트를 3번붙임

[1, 2, 10, 1, 2, 10, 1, 2, 10]

In [3]:
arr=np.array(list_1)
print(arr*3)
print(arr+100)

[ 3  6 30]
[101 102 110]


## 2차원 배열

In [6]:
data=[[1,2,3],[4,5,6],[7,8,9]]
print(data)
print(type(data))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [9]:
arr2=np.array(data)
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [10]:
arr2[1,2]  #[row,column]

6

In [11]:
arr2[1][2] #[row][column]

6

In [12]:
arr2[0] #0번째행

array([1, 2, 3])

In [16]:
arr2[:2,1:] #슬라이싱 1행부터 2행까지 / 1열부터 끝행

array([[2, 3],
       [5, 6]])

In [17]:
arr2[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

arange 함수

: numpy의 메소드

In [18]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
data=np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
data<4

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [21]:
data[data<4] # data[조건식] 조건식을 만족하는 것을 True인것만 추출 / 배열로 반환

array([0, 1, 2, 3])

In [23]:
data[data<4]=0 #True인 데이터만 0을 대입
data

array([[ 0,  0,  0],
       [ 0,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
data=np.arange(12).reshape(4,3)
data.mean() # 평균 계산 행렬 전부 평균

5.5

In [27]:
print(data.mean(axis=0)) #열방향 평균
print(data.mean(axis=1)) #행방향 평균

[4.5 5.5 6.5]
[ 1.  4.  7. 10.]


# pandas