<a href="https://colab.research.google.com/github/MATHKIMS/DSAC_license/blob/main/%5BDSAC_2%EC%A3%BC%EC%B0%A8%5Dgg_03_%5B2%EC%A3%BC%EC%B0%A8_(2)%5D_numpy%EC%99%80_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 

## 리스트와 배열

In [ ]:
import numpy as np
list_1=[1,2,10]
type(list_1)
list_1*3 #리스트의 연산은 리스트를 3번붙임

[1, 2, 10, 1, 2, 10, 1, 2, 10]

In [ ]:
arr=np.array(list_1)
print(arr*3)
print(arr+100)

[ 3  6 30]
[101 102 110]


## 2차원 배열

In [ ]:
data=[[1,2,3],[4,5,6],[7,8,9]]
print(data)
print(type(data))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [ ]:
arr2=np.array(data)
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
arr2[1,2]  #[row,column]

6

In [ ]:
arr2[1][2] #[row][column]

6

In [ ]:
arr2[0] #0번째행

array([1, 2, 3])

In [ ]:
arr2[:2,1:] #슬라이싱 1행부터 2행까지 / 1열부터 끝행

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

arange 함수

: numpy의 메소드

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
data=np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
data<4

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
data[data<4] # data[조건식] 조건식을 만족하는 것을 True인것만 추출 / 배열로 반환

array([0, 1, 2, 3])

In [ ]:
data[data<4]=0 #True인 데이터만 0을 대입
data

array([[ 0,  0,  0],
       [ 0,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
data=np.arange(12).reshape(4,3)
data.mean() # 평균 계산 행렬 전부 평균

5.5

In [ ]:
print(data.mean(axis=0)) #열방향 평균
print(data.mean(axis=1)) #행방향 평균

[4.5 5.5 6.5]
[ 1.  4.  7. 10.]


# pandas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dic={'city':['서울','부산','대전','대구','광주'],
     'year':[2017,2017,2018,2018,2018],
     'temp':[18,20,19,21,20]} #딕셔너리 정의
 
data=pd.DataFrame(dic) # 데이터프레임화
print(data)

  city  year  temp
0   서울  2017    18
1   부산  2017    20
2   대전  2018    19
3   대구  2018    21
4   광주  2018    20


In [ ]:
data[['year','city','temp']] #데이터프레임의 열의 위치를 바꿀땐 그냥 조건을 넣어주면 바뀜

year city  temp
0  2017   서울    18
1  2017   부산    20
2  2018   대전    19
3  2018   대구    21
4  2018   광주    20

In [ ]:
data

city  year  temp
0   서울  2017    18
1   부산  2017    20
2   대전  2018    19
3   대구  2018    21
4   광주  2018    20

In [ ]:
data=data[['year','city','temp']] # data변경
data

year city  temp
0  2017   서울    18
1  2017   부산    20
2  2018   대전    19
3  2018   대구    21
4  2018   광주    20

## (1) 인덱스 변경

In [ ]:
data.index=['a','b','c','d','e']
data

year city  temp
a  2017   서울    18
b  2017   부산    20
c  2018   대전    19
d  2018   대구    21
e  2018   광주    20

In [ ]:
list('abcde') #tips 문자열을 리스트로 반환

['a', 'b', 'c', 'd', 'e']

## (2) 컬럼 이름변경

In [ ]:
data.columns=['연도','도시','날씨']
data

연도  도시  날씨
a  2017  서울  18
b  2017  부산  20
c  2018  대전  19
d  2018  대구  21
e  2018  광주  20

## (3) 데이터의 값만 출력하는 방법 (열)

In [ ]:
data.연도 # 컬럼에 있는 값만 출력

a    2017
b    2017
c    2018
d    2018
e    2018
Name: 연도, dtype: int64

In [ ]:
data['연도'] # 컬럼에 있는 값만 출력

a    2017
b    2017
c    2018
d    2018
e    2018
Name: 연도, dtype: int64

## (4)데이터의 값 출력(인덱스)

In [ ]:
data

연도  도시  날씨
a  2017  서울  18
b  2017  부산  20
c  2018  대전  19
d  2018  대구  21
e  2018  광주  20

In [ ]:
data.loc['b'] #loc 행 (인덱스) 명을 조건으로 준다

연도    2017
도시      부산
날씨      20
Name: b, dtype: object

In [ ]:
data.iloc[2]

연도    2018
도시      대전
날씨      19
Name: c, dtype: object

In [ ]:
data.iloc[2:4]

연도  도시  날씨
c  2018  대전  19
d  2018  대구  21

In [ ]:
data.loc['c']

연도    2018
도시      대전
날씨      19
Name: c, dtype: object

# 열의 있는 한 피처를 인덱스로 변경

In [ ]:
data=data.set_index(['도시'])
data

연도  날씨
도시          
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [ ]:
data.set_index(['도시'],inplace=True)

## 컬럼추가

In [ ]:
cars=[50,40,20,30,10]

data['car']=cars # 컬럼추가 코드 
data

연도  날씨  car
도시               
서울  2017  18   50
부산  2017  20   40
대전  2018  19   20
대구  2018  21   30
광주  2018  20   10

In [ ]:
data['high']=data.car>=30
data

연도  날씨  car   high
도시                      
서울  2017  18   50   True
부산  2017  20   40   True
대전  2018  19   20  False
대구  2018  21   30   True
광주  2018  20   10  False

컬럼(열) 삭제

In [ ]:
data.drop(['car','high'],axis=1) #Data.drop(열리스트,축방향) 1:열 , 0은 행

연도  날씨
도시          
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

람다함수

: 특정 함수를 편리하게 전체 data에 일괄 적용하는 방법


간단한 함수 정의법

In [ ]:
f=lambda x: x.max()-x.min()

df=pd.DataFrame(np.arange(12).reshape(4,3),columns=list('ABC'),index=list('abcd'))
df

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

apply함수 

:데이터들을 적당한 함수를 정의한것을 적용해주는 함수

In [68]:
df.apply(f)

A    9
B    9
C    9
dtype: int64

In [69]:
df.apply(f,axis=1) #인덱스의 값만 적용

a    2
b    2
c    2
d    2
dtype: int64

In [72]:
pd.Series(['서울','부산','대전','대구','광주'], index=list('12345'))

1    서울
2    부산
3    대전
4    대구
5    광주
dtype: object

In [73]:
dic={'서울':800,'부산':150,'대구':100}
pd.Series(dic)

서울    800
부산    150
대구    100
dtype: int64